spring:
  application:
    name: Currency-Exchange-Service
  jpa:
    hibernate:
      ddl-auto: update
      
      
  datasource:
    url: jdbc:mysql://localhost:3306/currencydb?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
server:
  port: 8000
